site_name: TimetableSync
site_url: https://timetable.redbrick.dcu.ie/
repo_url: https://github.com/novanai/timetable-sync
nav:
  - Home: index.md
  - Timetable Generator: timetable.md
  - API Docs: docs.md
use_directory_urls: false
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins: []
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true